Update detect_api_changes.yml

diff --git a/.github/workflows/detect_api_changes.yml b/.github/workflows/detect_api_changes.yml
--- a/.github/workflows/detect_api_changes.yml
+++ b/.github/workflows/detect_api_changes.yml
@@ -19,19 +19,17 @@ permissions:
   issues: write
       
 jobs:
+
   build:
-    runs-on: macos-14 # Apple Silicon Runner
-    
+    runs-on: macos-14
+
     steps:
     - uses: actions/checkout@v4
-    - uses: n1hility/cancel-previous-runs@v3
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Select latest Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
-        xcode-version: '15.4'
+        xcode-version: '16.1'
         
     - name: 🚚 Fetch repo
       uses: actions/checkout@v4
@@ -40,13 +38,15 @@ jobs:
        
     - name: 👾 Define Diff Versions
       run: |
-        NEW="${{ env.source }}~${{ env.headGithubRepo }}"
-        OLD="${{ env.target }}~${{ env.baseGithubRepo }}"
+        NEW="${{ env.source }}~${{ env.githubRepo }}"
         
+        # Release branches get compared to the last tag instead of the target branch
         if [[ '${{ github.head_ref || env.noTargetBranch }}' == release/* ]]
         then
             LATEST_TAG=$(git describe --tags --abbrev=0)
-            OLD="$LATEST_TAG~${{ env.baseGithubRepo }}" 
+            OLD="$LATEST_TAG~${{ env.githubRepo }}"
+        else
+            OLD="${{ env.target }}~${{ env.githubRepo }}"
         fi
         
         # Providing the output to the environment
@@ -55,15 +55,71 @@ jobs:
       env:
         source: '${{ github.event.inputs.new || github.head_ref }}'
         target: '${{ github.event.inputs.old || github.event.pull_request.base.ref }}'
-        headGithubRepo: '${{github.server_url}}/${{ github.event.pull_request.head.repo.full_name || github.repository}}.git'
-        baseGithubRepo: '${{github.server_url}}/${{github.repository}}.git'
+        githubRepo: '${{github.server_url}}/${{github.repository}}.git'
         noTargetBranch: 'no target branch'
 
-    - name: 🔍 Detect Changes
-      if: env.skip_workflow != 'true'
-      uses: Adyen/adyen-swift-public-api-diff@0.7.0
-      id: public_api_diff
+    - uses: actions/checkout@v4
       with:
+        repository: "Adyen/adyen-swift-public-api-diff"
+        ref: "0.7.0"
+        path: "public-api-diff"
+
+    - name: 👾 Compute binary path
+      run: |
+        cd $GITHUB_WORKSPACE/public-api-diff
+        echo "BINARY_PATH=$(swift build --configuration release --show-bin-path)/public-api-diff" >> $GITHUB_ENV
+
+    - name: 🛻 Restore Binary
+      id: cache-restore
+      uses: actions/cache/restore@v3
+      with:
+        path: ${{ env.BINARY_PATH }}
+        key: build-cache-${{ runner.os }}-0.7.0
+
+    - name: 🧰 Build Swift CLI
+      if: steps.cache-restore.outputs.cache-hit != 'true'
+      run: |
+        cd $GITHUB_WORKSPACE/public-api-diff
+        swift build --configuration release
+
+    - name: 🪪 Verify binary exists
+      run: |
+        if [ ! -f ${{ env.BINARY_PATH }} ]; then 
+          echo "Binary not found at ${{ env.BINARY_PATH }} after build" 
+          exit 1
+        else 
+          echo "Binary found at ${{ env.BINARY_PATH }}" 
+        fi
+
+    - name: 💾 Save Binary
+      if: steps.cache-restore.outputs.cache-hit != 'true'
+      uses: actions/cache/save@v3
+      with:
+        path: ${{ env.BINARY_PATH }}
+        key: build-cache-${{ runner.os }}-0.7.0
+        
+    - name: "🏃 Run Diff"
+      run: |
+        NEW=${{ env.NEW_VERSION }}
+        OLD=${{ env.OLD_VERSION }}
+        PLATFORM=${{ env.platform }}
+        BINARY_PATH=${{ env.BINARY_PATH }}
+                
+        PROJECT_FOLDER=$PWD
+        echo $PROJECT_FOLDER
+        
+        $BINARY_PATH project --new "$NEW" --old "$OLD" --platform "$PLATFORM" --output "$PROJECT_FOLDER/api_comparison.md" --log-output "$PROJECT_FOLDER/logs.txt"
+        
+        cat "$PROJECT_FOLDER/logs.txt"
+        
+        cat "$PROJECT_FOLDER/api_comparison.md" >> $GITHUB_STEP_SUMMARY
+      env:
         platform: "iOS"
-        new: ${{ env.NEW_VERSION }}
-        old: ${{ env.OLD_VERSION }}
+      
+    - if: ${{ github.event.pull_request.base.ref != '' }}
+      name: 📝 Comment on PR
+      uses: thollander/actions-comment-pull-request@v3
+      with:
+        file-path: "${{ github.workspace }}/api_comparison.md"
+        comment-tag: api_changes
+        mode: recreate
